services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8181:8080"